### **1\. 介绍（Introduction）**

> **Koa -- 基于 Node.js 的下一代 web 开发框架**  
> Koa 是一个新的 web 框架，由 Express 幕后的原班人马打造， 致力于成为 web 应用和 API 开发领域中的一个更小、更富有表现力、更健壮的基石。 通过利用 async 函数，Koa 帮你丢弃回调函数，并有力地增强错误处理。 Koa 并没有捆绑任何中间件， 而是提供了一套优雅的方法，帮助您快速而愉快地编写服务端应用程序。

### **2\. 环境 （Environment）**

*   Node 版本在 v.7.6 以上

### **3\. Hello World**

*   初始化

```
# 初始化一个项目文件夹 demo
mkdir demo
# 初始化 package.json 文件
npm init -y
# 安装 koa
npm i koa
# 新建项目入口文件
touch index.js
```

*   编写代码

```
// index.js const Koa = require('koa')
const app = new Koa()
app.use(ctx => {
    ctx.body = 'hello world'
})
app.listen(3000) 
```

*   运行

打开 [http://localhost:3000](https://link.zhihu.com/?target=http%3A//localhost%3A3000/) 即可看见服务端返回的 hello world

### **4\. Context对象**

Koa 提供一个 Context 对象，表示一次对话的上下文（Http Request and Http Response），上述代码中的 `ctx`，即为 Context 对象的缩写。

*   `ctx.request:`请求数据
*   `ctx.response:`响应数据

### **5\. 级联(中间件栈)**

```ts
// index.js const Koa = require('koa')
const app = new Koa()
​
// one two three 可称之为中间件（Middleware） const one = (ctx, next) => {
  console.log('>> one');
  next();
  console.log('<< one');
}
​
const two = (ctx, next) => {
  console.log('>> two');
  next(); 
  console.log('<< two');
}
​
const three = (ctx, next) => {
  console.log('>> three');
  next();
  console.log('<< three');
}
​
app.use(one);
app.use(two);
app.use(three);
​
app.listen(3000) 
```

运行结果如下：

```
>> one
>> two
>> three
<< three
<< two
<< one
```

**解析：** 

`next()：`直接进入下一个中间件的逻辑。

所以：

*   执行 **one**，打印 `>> one`
*   进入 **two**，打印 `>> two`
*   进入 **three**，打印 `>> three`，没有下一个中间件，打印 `<< three`
*   返回 **two**，打印 `<< two`
*   返回 **one**，打印 `<< one`

### **6\. 路由（router）**

### **6.1 原生路由**

```js
// index.js const Koa = require('koa')
const app = new Koa()
​
// 原生路由 const main = ctx => {
    if (ctx.path === '/') {
        ctx.body = 'home page'
    } else if (ctx.path === '/about') {
        ctx.body = 'about page'
    }
}
​
app.use(main)
app.listen(3000) 
```

运行项目：访问[http://localhost:3000](https://link.zhihu.com/?target=http%3A//localhost%3A3000/) 显示 home page ，访问 [http://localhost:3000/about](https://link.zhihu.com/?target=http%3A//localhost%3A3000/about) 显示 about page

### **6.2 路由中间件（koa-route）**

```js
npm i koa-route -S
// index.js
const Koa = require('koa')
const app = new Koa()
const route = require('koa-route')
​
const main = ctx => {
    ctx.body = 'home page'
}
​
const about = ctx => {
    ctx.body = 'about page'
}
​
app.use(route.get('/', main))
app.use(route.get('/about', about))
app.listen(3000)
```

效果和上述原生路由一致

### **7\. 静态资源（koa-static 中间件）**

```js
npm i koa-static -S
// index.js
const Koa = require('koa')
const app = new Koa()
const path = require('path')
const serve = require('koa-static')
​
// 开放当前文件夹为 public 文件夹
const main = serve(path.join(__dirname))
app.use(main)
app.listen(3000)
```

浏览器访问 [http://localhost:3000/index.js](https://link.zhihu.com/?target=http%3A//localhost%3A3000/index.js) 即可看到当前 js 文件的脚本内容在浏览器端展示。

### **8\. 异步中间件**

异步操作可以借助 ES6 的 `async` 和 `await` 语法将异步函数转化成同步来调用，减少代码嵌套。

```js
const Koa = require('koa')
const app = new Koa()
const fs = require('fs')
​
// 假定当前文件夹下存在一个 template.html 的文件 const main = async function (ctx, next) {
  ctx.response.type = 'html'
  ctx.response.body = await fs.readFile('./template.html', 'utf8')
}
​
app.use(main)
app.listen(3000) 
```

运行项目即可看见 template.html 的内容。

### **9\. 错误处理**

代码在运行的过程中发生错误，服务端需要将错误信息返回给用户，Koa 提供了一个 `ctx.throw()`方法，用于抛出一个错误。

```
// 抛出一个500的错误，访问 http://127.0.0.1:3000，你会看到一个500错误页"Internal Server Error"。 const main = ctx => {
    ctx.throw(500)
}
// 抛出一个 404 的错误，访问 http://127.0.0.1:3000，你会看到一个404错误页"Not Found"。 const about = ctx => {
    ctx.throw(404)
} 
```

> **错误处理的中间件**

有时候为了让程序出错但是不影响程序运行，经常需要用 `try...catch`用于捕获错误，但是要为每一个中间件都用 `try...catch` 包裹未免就显得很麻烦了。所以可以专门编写一个错误处理的中间件，用于捕获程序中发生的错误，负责错误处理。

```js
const Koa = require('koa')
const app = new Koa()
​
// handler 中间件会首先执行，此后的所有中间件如果发生错误都会被捕获，进行错误信息的返回。 const handler = async (ctx, next) => {
  try {
    await next();
  } catch (err) {
    ctx.response.status = err.statusCode || err.status || 500;
    ctx.response.body = {
      message: err.message
    };
  }
};
​
const main = ctx => {
  ctx.throw(500);
};
​
app.use(handler)
app.use(main)
app.listen(3000) 
```